//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BLL.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date;ClientId;ProductId;Sum
        ///23.12.2019;ѓ ©¤Ґ«м €аЁ­  €ў ­®ў­ ;Ѓ®вЁ­ЄЁ;150
        ///23.12.2019;ѓ ©¤Ґ«м €аЁ­  €ў ­®ў­ ;Љ®дв ;200
        ///23.12.2019;ѓ ©¤Ґ«м €аЁ­  €ў ­®ў­ ;ЉгавЄ ;1000
        ///24.12.2019;ѓ ©¤Ґ«м ‹Ґў Ђ«ҐЄбҐҐўЁз; ЇЄ ;100
        ///24.12.2019;ѓ ©¤Ґ«м ‹Ґў Ђ«ҐЄбҐҐўЁз;ЉгавЄ ;500
        ///24.12.2019;ѓ ©¤Ґ«м ‹Ґў Ђ«ҐЄбҐҐўЁз;Ѓ®вЁ­ЄЁ;600
        ///24.12.2019;ѓ ©¤Ґ«м ‹Ґў Ђ«ҐЄбҐҐўЁз;Љ®дв ;300
        ///25.12.2019;€ў ­®ў €ў ­ €ў ­®ўЁз;ЃаоЄЁ;250
        ///25.12.2019;€ў ­®ў €ў ­ €ў ­®ўЁз; ад;100
        ///25.12.2019;€ў ­®ў €ў ­ €ў ­®ўЁз;Џ «мв®;1500
        ///25.12.2019;ЏҐва®ў ЏҐва ЏҐва®ўЁз [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Ivanov_08012020 {
            get {
                return ResourceManager.GetString("Ivanov_08012020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date;ClientId;ProductId;Sum
        ///23.12.2019;ѓ ©¤Ґ«м €аЁ­  €ў ­®ў­ ;Ѓ®вЁ­ЄЁ;150
        ///23.12.2019;ѓ ©¤Ґ«м €аЁ­  €ў ­®ў­ ;Љ®дв ;200
        ///23.12.2019;ѓ ©¤Ґ«м €аЁ­  €ў ­®ў­ ;ЉгавЄ ;1000
        ///24.12.2019;ѓ ©¤Ґ«м ‹Ґў Ђ«ҐЄбҐҐўЁз; ЇЄ ;100
        ///24.12.2019;ѓ ©¤Ґ«м ‹Ґў Ђ«ҐЄбҐҐўЁз;ЉгавЄ ;500
        ///24.12.2019;ѓ ©¤Ґ«м ‹Ґў Ђ«ҐЄбҐҐўЁз;Ѓ®вЁ­ЄЁ;600
        ///24.12.2019;ѓ ©¤Ґ«м ‹Ґў Ђ«ҐЄбҐҐўЁз;Љ®дв ;300
        ///25.12.2019;€ў ­®ў €ў ­ €ў ­®ўЁз;ЃаоЄЁ;250
        ///25.12.2019;€ў ­®ў €ў ­ €ў ­®ўЁз; ад;100
        ///25.12.2019;€ў ­®ў €ў ­ €ў ­®ўЁз;Џ «мв®;1500
        ///25.12.2019;ЏҐва®ў ЏҐва ЏҐва®ўЁз [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Ivanov_19112012 {
            get {
                return ResourceManager.GetString("Ivanov_19112012", resourceCulture);
            }
        }
    }
}
